# Generated by Django 4.2.7 on 2025-08-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='package_range',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='company',
            name='salary_range',
            field=models.CharField(blank=True, help_text='e.g., 5-10 LPA', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='tier',
            field=models.CharField(blank=True, choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3'), ('startup', 'Startup'), ('mnc', 'MNC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='ChallengeSubmission',
        ),
        migrations.DeleteModel(
            name='DailyChallenge',
        ),
    ]
