# Generated by Django 4.2.7 on 2025-08-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('question', 'Question'), ('notes', 'Notes/Documents'), ('tip', 'Tip/Trick'), ('resource', 'Resource')], default='question', max_length=20),
        ),
    ]
