# Generated by Django 4.2.7 on 2025-08-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo_url',
        ),
    ]
